//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JneCommSitesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ActivityLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ActivityLog()
        {
            this.T_FilesUploadedBySiteTaskProgress = new HashSet<T_FilesUploadedBySiteTaskProgress>();
            this.T_Purchase = new HashSet<T_Purchase>();
            this.T_TaskProgress = new HashSet<T_TaskProgress>();
        }
    
        public int iActivityLogID { get; set; }
        public string Id { get; set; }
        public string vSiteName { get; set; }
        public System.DateTime dtStartWorkingDay { get; set; }
        public string vStartWorkingDayPosition { get; set; }
        public Nullable<System.DateTime> dtArrivingToWareHouse { get; set; }
        public string vArrivingToWareHousePosition { get; set; }
        public Nullable<System.DateTime> dtDepartureFromWereHouse { get; set; }
        public string vDepartureFromWereHousePosition { get; set; }
        public Nullable<System.DateTime> dtEndWorkingDay { get; set; }
        public string vEndWorkingDayPosition { get; set; }
        public Nullable<int> iProgress { get; set; }
        public string vNotes { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual T_Sites T_Sites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FilesUploadedBySiteTaskProgress> T_FilesUploadedBySiteTaskProgress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Purchase> T_Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TaskProgress> T_TaskProgress { get; set; }
    }
}
