//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JneCommSitesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Operations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Operations()
        {
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public short biOperationsId { get; set; }
        public string vControllerName { get; set; }
        public string vOperationName { get; set; }
        public string vDisplayTittle { get; set; }
        public Nullable<short> iParentOper { get; set; }
        public bool bIsVisible { get; set; }
        public bool bIsActive { get; set; }
        public bool bRequieresPermission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
