//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JneCommSitesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserData
    {
        public string UserID { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public bool LockoutEnabled { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public string RoleID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserDescription { get; set; }
        public Nullable<short> NumDaysForPassChange { get; set; }
        public Nullable<System.DateTime> PassRecoveryDate { get; set; }
        public string PassRecovery { get; set; }
        public Nullable<bool> ForcePassChange { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsBilingual { get; set; }
        public Nullable<decimal> LaborHourPay { get; set; }
        public string vStateName { get; set; }
        public string vStateCode { get; set; }
    }
}
